# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

# Added this because appveyor was failing with tibble.
# Probably temporary because CRAN doesn't have binary package
# https://github.com/r-lib/ps/issues/52
environment:
  global:
    USE_RTOOLS: true
    R_CHECK_INSTALL_ARGS: "--install-args=--build --no-multiarch "
  matrix:
    - R_VERSION: release
      R_VER: 3.5

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - if not exist "C:\rtm" mkdir C:\rtm
  - set TMP=C:/rtm
  - set TEMP=C:/rtm
  - set TMPDIR=C:/rtm
  - ps: Invoke-WebRequest https://github.com/stnava/ITKR/releases/download/v0.4.17.5.1/ITKR_0.4.17.5_R3.5.zip -OutFile ".\ITKR.zip"
  - Rscript -e "install.packages('ITKR.zip', repos = NULL)"
  - rm ITKR.zip
  # - git clone https://github.com/stnava/ITKR
  # - R CMD INSTALL ITKR
  - Rscript -e "x = read.dcf('DESCRIPTION'); x = as.data.frame(x, stringsAsFactors = FALSE); x$Remotes = NULL; write.dcf(x, 'DESCRIPTION');"
  # need to move to higher dir because CMake path req
  - if not exist "C:\run" mkdir C:\run
  - cp -avr * C:\run
  # need the tool a level above
  - cp ../travis-tool.sh C:\
  - cd C:\run
  # - ps: Invoke-WebRequest http://ci.appveyor.com/api/buildjobs/tu3s6m73682lhvc1/artifacts/ITKR_0.4.12.3.zip -OutFile ".\ITKR.zip"
  # - ps: Invoke-WebRequest https://github.com/muschellij2/ITKR/releases/download/v0.4.12.2/ITKR_0.4.12.2.zip -OutFile ".\ITKR.zip"
  # - ls
  # - Rscript -e "install.packages('ITKR.zip', repos = NULL)"
  # - rm ITKR.zip
  # # Install castxml
  # - wget -O travis_helpers.sh --no-check-certificate http://bit.ly/travis_helpers
  # - cat travis_helpers.sh
  # - bash travis_helpers.sh
  # - ps: echo '@bash.exe ./travis_helpers.sh %*' | Out-File -Encoding ASCII ./travis_helpers.sh.cmd
  # - cat DESCRIPTION
  # - travis_helpers.sh drop_remote ITKR
  # - cat DESCRIPTION
  # setting PATH to be specific - no MinGW overall - just R's
  - ps: echo "${PATH}"
  - ps: echo "${LD_LIBRARY_PATH}"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
